# A simple network topology for Project Aegis with latency values

nodes:
  - name: Ground Station Alpha
  - name: Command Center
  - name: Mobile Unit 7
  - name: Satellite Relay
  - name: Backup Center

links:
  # [node1, node2, latency_in_ms]
  # Fast, direct links
  - [Command Center, Mobile Unit 7, 20]
  - [Satellite Relay, Backup Center, 40]
  
  # Slower, terrestrial links
  - [Command Center, Ground Station Alpha, 50]
  - [Ground Station Alpha, Backup Center, 60]

  # High-latency satellite link
  - [Command Center, Satellite Relay, 150]